name: 'Omni Repo - Tag'
description: 'Github Action for pushing supplied tags to the remote repository'
author: 'aabenoja'
inputs:
  github_token:
    required: true
    description: 'Needed to push release tags'
  version_map:
    required: true
    description: 'A JSON object that maps projects to the tag to give them'
runs:
  using: 'node12'
  main: 'dist/index.js'
